import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";



export const metadata: Metadata = {
  title: "RIRA Company Notes Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"
          async
        ></script>
      </Head>
      <body>
        {children}

      </body>
    </html>
  );
}
